# Generated by Django 3.2.12 on 2022-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='img',
            field=models.ImageField(default='defff', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
